CREATE TABLE Customer (
    CustomerID INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(100) NOT NULL,
    Email VARCHAR(100) UNIQUE NOT NULL,
    PhoneNumber VARCHAR(15),
    Address VARCHAR(255),
    Password VARCHAR(255) NOT NULL
);

CREATE TABLE Restaurant (
    RestaurantID INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(100) NOT NULL,
    Location VARCHAR(255),
    ContactNumber VARCHAR(15),
    CuisineType VARCHAR(100),
    Rating FLOAT DEFAULT 0.0
);

CREATE TABLE MenuItem (
    MenuItemID INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(100) NOT NULL,
    Price FLOAT NOT NULL,
    Description TEXT,
    Category VARCHAR(100),
    Rating FLOAT DEFAULT 0.0,
    RestaurantID INT NOT NULL,
    FOREIGN KEY (RestaurantID) REFERENCES Restaurant(RestaurantID) ON DELETE CASCADE
);

CREATE TABLE "Order" (
    OrderID INT AUTO_INCREMENT PRIMARY KEY,
    OrderDate DATETIME DEFAULT CURRENT_TIMESTAMP,
    TotalAmount FLOAT,
    Status VARCHAR(50),
    TimeToReach TIME,
    Rating FLOAT DEFAULT 0.0,
    CustomerID INT NOT NULL,
    RestaurantID INT NOT NULL,
    FOREIGN KEY (CustomerID) REFERENCES Customer(CustomerID) ON DELETE CASCADE,
    FOREIGN KEY (RestaurantID) REFERENCES Restaurant(RestaurantID) ON DELETE CASCADE
);

CREATE TABLE OrderItem (
    OrderItemID INT AUTO_INCREMENT PRIMARY KEY,
    Quantity INT NOT NULL,
    Price FLOAT NOT NULL,
    MenuItemID INT NOT NULL,
    OrderID INT NOT NULL,
    FOREIGN KEY (MenuItemID) REFERENCES MenuItem(MenuItemID) ON DELETE CASCADE,
    FOREIGN KEY (OrderID) REFERENCES "Order"(OrderID) ON DELETE CASCADE
);

CREATE TABLE DeliveryPerson (
    DeliveryPersonID INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(100) NOT NULL,
    PhoneNumber VARCHAR(15),
    VehicleDetails VARCHAR(100),
    Rating FLOAT DEFAULT 0.0
);

CREATE TABLE Payment (
    PaymentID INT AUTO_INCREMENT PRIMARY KEY,
    PaymentDate DATETIME DEFAULT CURRENT_TIMESTAMP,
    PaymentMethod VARCHAR(50),
    PaymentStatus VARCHAR(50),
    Amount FLOAT,
    OrderID INT NOT NULL,
    FOREIGN KEY (OrderID) REFERENCES "Order"(OrderID) ON DELETE CASCADE
);

CREATE TABLE CartItem (
    CartItemID INT AUTO_INCREMENT PRIMARY KEY,
    CustomerID INT NOT NULL,
    MenuItemID INT NOT NULL,
    RestaurantID INT NOT NULL,
    Quantity INT NOT NULL DEFAULT 1,
    FOREIGN KEY (CustomerID) REFERENCES Customer(CustomerID) ON DELETE CASCADE,
    FOREIGN KEY (MenuItemID) REFERENCES MenuItem(MenuItemID) ON DELETE CASCADE,
    FOREIGN KEY (RestaurantID) REFERENCES Restaurant(RestaurantID) ON DELETE CASCADE
);
