"""database migration

Revision ID: 4f4242864de4
Revises: 
Create Date: 2024-11-30 20:20:17.336187

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f4242864de4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer',
    sa.Column('CustomerID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Name', sa.String(length=100), nullable=False),
    sa.Column('Email', sa.String(length=100), nullable=False),
    sa.Column('PhoneNumber', sa.String(length=15), nullable=True),
    sa.Column('Address', sa.String(length=255), nullable=True),
    sa.Column('Password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('CustomerID'),
    sa.UniqueConstraint('Email')
    )
    op.create_table('delivery_person',
    sa.Column('DeliveryPersonID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Name', sa.String(length=100), nullable=False),
    sa.Column('PhoneNumber', sa.String(length=15), nullable=True),
    sa.Column('VehicleDetails', sa.String(length=100), nullable=True),
    sa.Column('Rating', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('DeliveryPersonID')
    )
    op.create_table('restaurant',
    sa.Column('RestaurantID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Name', sa.String(length=100), nullable=False),
    sa.Column('Location', sa.String(length=255), nullable=True),
    sa.Column('ContactNumber', sa.String(length=15), nullable=True),
    sa.Column('CuisineType', sa.String(length=100), nullable=True),
    sa.Column('Rating', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('RestaurantID')
    )
    op.create_table('menu_item',
    sa.Column('MenuItemID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Name', sa.String(length=100), nullable=False),
    sa.Column('Price', sa.Float(), nullable=False),
    sa.Column('Description', sa.Text(), nullable=True),
    sa.Column('Category', sa.String(length=100), nullable=True),
    sa.Column('Rating', sa.Float(), nullable=True),
    sa.Column('RestaurantID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['RestaurantID'], ['restaurant.RestaurantID'], ),
    sa.PrimaryKeyConstraint('MenuItemID')
    )
    op.create_table('order',
    sa.Column('OrderID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('OrderDate', sa.DateTime(), nullable=True),
    sa.Column('TotalAmount', sa.Float(), nullable=True),
    sa.Column('Status', sa.String(length=50), nullable=True),
    sa.Column('TimeToReach', sa.Time(), nullable=True),
    sa.Column('Rating', sa.Float(), nullable=True),
    sa.Column('CustomerID', sa.Integer(), nullable=False),
    sa.Column('RestaurantID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['CustomerID'], ['customer.CustomerID'], ),
    sa.ForeignKeyConstraint(['RestaurantID'], ['restaurant.RestaurantID'], ),
    sa.PrimaryKeyConstraint('OrderID')
    )
    op.create_table('cart_item',
    sa.Column('CartItemID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('CustomerID', sa.Integer(), nullable=False),
    sa.Column('MenuItemID', sa.Integer(), nullable=False),
    sa.Column('Quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['CustomerID'], ['customer.CustomerID'], ),
    sa.ForeignKeyConstraint(['MenuItemID'], ['menu_item.MenuItemID'], ),
    sa.PrimaryKeyConstraint('CartItemID')
    )
    op.create_table('order_item',
    sa.Column('OrderItemID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Quantity', sa.Integer(), nullable=False),
    sa.Column('Price', sa.Float(), nullable=False),
    sa.Column('MenuItemID', sa.Integer(), nullable=False),
    sa.Column('OrderID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['MenuItemID'], ['menu_item.MenuItemID'], ),
    sa.ForeignKeyConstraint(['OrderID'], ['order.OrderID'], ),
    sa.PrimaryKeyConstraint('OrderItemID')
    )
    op.create_table('payment',
    sa.Column('PaymentID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('PaymentDate', sa.DateTime(), nullable=True),
    sa.Column('PaymentMethod', sa.String(length=50), nullable=True),
    sa.Column('PaymentStatus', sa.String(length=50), nullable=True),
    sa.Column('Amount', sa.Float(), nullable=True),
    sa.Column('OrderID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['OrderID'], ['order.OrderID'], ),
    sa.PrimaryKeyConstraint('PaymentID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payment')
    op.drop_table('order_item')
    op.drop_table('cart_item')
    op.drop_table('order')
    op.drop_table('menu_item')
    op.drop_table('restaurant')
    op.drop_table('delivery_person')
    op.drop_table('customer')
    # ### end Alembic commands ###
