"""empty message

Revision ID: e4865cc43fe0
Revises: 4f4242864de4
Create Date: 2024-12-01 13:13:28.814848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4865cc43fe0'
down_revision = '4f4242864de4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('RestaurantID', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'restaurant', ['RestaurantID'], ['RestaurantID'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart_item', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('RestaurantID')

    # ### end Alembic commands ###
